import { AbilityDetails, AbilityType, ItemType, StageConfig } from '../types/game';

export const ABILITIES: Record<AbilityType, AbilityDetails> = {
  Normal: {
    id: 'Normal',
    name: '無能力 (波波)',
    nameEn: 'Normal',
    color: '#F472B6', // pink-400
    accentColor: '#EC4899',
    icon: '🌸',
    description: '圓滾滾的棉花糖生物。可以吸入敵人、吐出星彈、鼓氣飛行與滑行踢擊。',
    moves: ['【吸入】長按 J', '【星彈】含住時按 J', '【吞入胃袋】按 S 或 下鍵', '【滑踢】下 + J', '【飛行】空中連按 W/跳躍'],
  },
  Sword: {
    id: 'Sword',
    name: '劍士',
    nameEn: 'Sword',
    color: '#22C55E', // green-500
    accentColor: '#16A34A',
    icon: '⚔️',
    description: '綠色勇者帽與敏捷長劍，擁有經典的多段連續斬擊與迴旋斬。滿血時能揮出劍氣！',
    moves: ['【連環斬】連續按 J', '【迴旋斬】衝刺中按 J', '【滿血劍氣】生命全滿時揮劍發射', '【上挑斬】上 + J'],
  },
  Fire: {
    id: 'Fire',
    name: '火焰',
    nameEn: 'Fire',
    color: '#EF4444', // red-500
    accentColor: '#DC2626',
    icon: '🔥',
    description: '頭頂熊熊烈火王冠。能向前噴吐高溫火焰，點燃導火線與燒毀荊棘藤蔓！',
    moves: ['【火焰噴射】按住 J（可用上下鍵調整仰角）', '【烈焰衝刺】衝刺中按 J 變身火球', '【點燃機制】可燒毀枯木藤蔓與點燃炸藥桶'],
  },
  Ice: {
    id: 'Ice',
    name: '寒冰',
    nameEn: 'Ice',
    color: '#38BDF8', // sky-400
    accentColor: '#0284C7',
    icon: '❄️',
    description: '散發極寒風雪的冰雪王冠。可將雜兵凍結成冰塊踢出，或凍結水面形成冰橋。',
    moves: ['【暴風雪噴射】長按 J 噴吐冷氣', '【踢冰塊】將凍結的敵人當作滑行重砲踢出', '【凍結水面】在水上使用寒氣可形成可步行的冰塊踏板'],
  },
  Spark: {
    id: 'Spark',
    name: '電擊 / 雷霆',
    nameEn: 'Spark',
    color: '#EAB308', // yellow-500
    accentColor: '#CA8A04',
    icon: '⚡',
    description: '頭戴高壓避雷耳機。能張開防護罩電擊四周，蓄力後可發射穿透雷霆衝擊波！',
    moves: ['【電磁防護罩】按住 J 釋放四周電場', '【雷霆衝擊波】連打 J 蓄力發射強大電球', '【通電機制】可啟動關卡中的古代電極開關'],
  },
  Bomb: {
    id: 'Bomb',
    name: '炸彈',
    nameEn: 'Bomb',
    color: '#6366F1', // indigo-500
    accentColor: '#4F46E5',
    icon: '💣',
    description: '戴著海盜頭巾的爆破大師。可投擲或滾動定時炸彈，破壞岩石或障礙。',
    moves: ['【投擲炸彈】按 J 取出並投擲（長按可調整拋物線）', '【設置地雷】下 + J 將炸彈放在腳邊', '【爆破岩石】能炸開硬質岩石方塊'],
  },
  FireSword: {
    id: 'FireSword',
    name: '烈焰劍',
    nameEn: 'Fire Sword',
    color: '#F97316', // orange-500
    accentColor: '#EA580C',
    icon: '🔥⚔️',
    description: '【胃袋融合技】火焰與劍士結合的霸道雙屬性！劍刃燃燒超高溫烈焰，斬擊帶有火柱！',
    moves: ['【烈焰斬】每次揮劍引發劇烈火浪', '【烈焰迴旋斬】衝刺 J 形成環形火風暴', '【同時具備】斬擊斷木、點燃導火線、超高範圍傷害'],
    isFused: true,
  },
  IceSword: {
    id: 'IceSword',
    name: '寒冰劍',
    nameEn: 'Ice Sword',
    color: '#06B6D4', // cyan-500
    accentColor: '#0891B2',
    icon: '❄️⚔️',
    description: '【胃袋融合技】寒冰與劍士結合的極寒兵刃！劍光所過之處盡皆冰封，能揮出冰晶月牙。',
    moves: ['【極霜月牙】揮劍釋放飛行冰霜劍氣', '【冰霜衝刺斬】衝刺 J 劃破空氣凍結沿途所有敵人', '【立即凍水】劍擊落水可直接凝結大面積冰台'],
    isFused: true,
  },
  ThunderSword: {
    id: 'ThunderSword',
    name: '雷霆劍',
    nameEn: 'Thunder Sword',
    color: '#FACC15', // yellow-400
    accentColor: '#EAB308',
    icon: '⚡⚔️',
    description: '【胃袋融合技】電擊與劍士結合的閃電神劍！劍尖激盪十萬伏特電弧，可引導連鎖閃電！',
    moves: ['【雷霆連斬】揮劍附帶連鎖電弧打擊全體敵人', '【雷光突刺】衝刺 J 疾風電光穿透障礙', '【遠距通電】劍氣可遠程啟動電極開關'],
    isFused: true,
  },
  FireBomb: {
    id: 'FireBomb',
    name: '火焰爆彈',
    nameEn: 'Fire Bomb',
    color: '#EF4444',
    accentColor: '#B91C1C',
    icon: '🔥💣',
    description: '【胃袋融合技】火焰與炸彈融合。爆炸時爆發漫天流火，在地面留下持續燃燒的火海！',
    moves: ['【燃燒爆彈】投擲高威力凝固汽油彈', '【地面火海】爆炸後在地面燃燒數秒，重創敵人'],
    isFused: true,
  },
  IceBomb: {
    id: 'IceBomb',
    name: '寒冰爆彈',
    nameEn: 'Ice Bomb',
    color: '#38BDF8',
    accentColor: '#0369A1',
    icon: '❄️💣',
    description: '【胃袋融合技】寒冰與炸彈融合。爆炸釋放急速低溫衝擊波，大範圍瞬間冰封所有雜兵！',
    moves: ['【急凍炸彈】投擲霜凍手榴彈', '【極低溫領域】半徑內所有敵人全部瞬間凝結為冰塊！'],
    isFused: true,
  },
  SuperStar: {
    id: 'SuperStar',
    name: '大超星',
    nameEn: 'Super Star',
    color: '#FDE047',
    accentColor: '#EAB308',
    icon: '🌟',
    description: '由兩顆氣泡或星星強力融合誕生的超能星！使用可引發全螢幕流星震撼打擊！',
    moves: ['【全螢幕流星】點擊胃袋氣泡，瞬間擊退並秒殺全場雜兵與盜賊！'],
    isFused: true,
  },
};

export const STAGES: StageConfig[] = [
  {
    id: 1,
    title: '第一關：綠色微風平原',
    subtitle: 'Sunny Green Meadows',
    theme: 'meadow',
    width: 2400,
    height: 480,
    bgGradient: ['#38BDF8', '#86EFAC'],
    hasGoldenChest: true,
    hasSilverChest: true,
    musicTrack: 'stage1',
    chestReward: {
      type: 'scroll',
      title: '劍士奧義秘卷 📜',
      description: '解鎖劍士【滿血劍氣】與【空中下落刺】，讓長劍威力大幅強化！',
      abilityTarget: 'Sword',
    },
  },
  {
    id: 2,
    title: '第二關：冰川晶石窟',
    subtitle: 'Frosty Crystal Cavern',
    theme: 'cavern',
    width: 2600,
    height: 480,
    bgGradient: ['#1E1B4B', '#312E81'],
    hasGoldenChest: true,
    hasSilverChest: true,
    musicTrack: 'stage2',
    chestReward: {
      type: 'scroll',
      title: '火焰奧義秘卷 📜',
      description: '火焰衝刺進化為【不死鳥烈焰】，撞擊時產生巨大範圍爆震！',
      abilityTarget: 'Fire',
    },
  },
  {
    id: 3,
    title: '第三關：怪盜飛空要塞',
    subtitle: 'Rogues Flying Fortress',
    theme: 'fortress',
    width: 2800,
    height: 480,
    bgGradient: ['#311042', '#701A75'],
    hasGoldenChest: true,
    hasSilverChest: true,
    musicTrack: 'boss',
    chestReward: {
      type: 'cake',
      title: '究極草莓千層酥 🍰👑',
      description: '傳說中被怪盜團首領奪走的夢幻極品甜點！奪回它，享受無上的野餐幸福！',
    },
  },
];
